import { WelcomePage } from "@/pageblock/WelcomePage/WelcomePage";

export default function Home() {
    return (
        <div className="flex items-center justify-start md:p-0 flex-col">
            <WelcomePage />
            <div className="flex px-16 ">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim blandit volutpat maecenas volutpat. Leo vel fringilla est ullamcorper eget nulla. Venenatis cras sed felis eget velit aliquet sagittis. Lectus arcu bibendum at varius vel pharetra. Tristique nulla aliquet enim tortor at auctor urna nunc. Commodo elit at imperdiet dui accumsan sit amet nulla facilisi. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Et malesuada fames ac turpis egestas sed tempus urna. Elit pellentesque habitant morbi tristique senectus et. Turpis tincidunt id aliquet risus feugiat in ante metus. Erat velit scelerisque in dictum non consectetur a erat nam. Ut eu sem integer vitae justo eget magna fermentum iaculis. A arcu cursus vitae congue mauris rhoncus aenean. Justo nec ultrices dui sapien eget mi proin sed libero. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Facilisis gravida neque convallis a cras semper auctor. In ante metus dictum at tempor commodo ullamcorper.

                Donec ultrices tincidunt arcu non sodales neque. Quis imperdiet massa tincidunt nunc pulvinar. Neque aliquam vestibulum morbi blandit cursus risus. Volutpat odio facilisis mauris sit amet massa vitae tortor. Ornare arcu odio ut sem. Nullam non nisi est sit amet facilisis magna. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Blandit aliquam etiam erat velit scelerisque in dictum non. Facilisi cras fermentum odio eu feugiat pretium. Aliquam id diam maecenas ultricies mi. Ut morbi tincidunt augue interdum velit euismod in pellentesque.

                Nunc aliquet bibendum enim facilisis gravida neque convallis a cras. Auctor augue mauris augue neque gravida in fermentum et. Habitant morbi tristique senectus et netus et malesuada fames ac. Diam vel quam elementum pulvinar etiam non quam. Semper auctor neque vitae tempus quam. Sed enim ut sem viverra aliquet eget sit amet. Sit amet aliquam id diam maecenas. Arcu vitae elementum curabitur vitae nunc. Vitae purus faucibus ornare suspendisse sed nisi lacus. Sed sed risus pretium quam vulputate dignissim suspendisse.

                Pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Tellus orci ac auctor augue mauris augue neque gravida. In hendrerit gravida rutrum quisque non tellus orci ac auctor. Nunc faucibus a pellentesque sit amet porttitor eget. Neque aliquam vestibulum morbi blandit cursus. Diam ut venenatis tellus in metus. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Tempor commodo ullamcorper a lacus vestibulum sed. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget. Maecenas volutpat blandit aliquam etiam. Pretium viverra suspendisse potenti nullam ac tortor vitae purus. Lacus sed turpis tincidunt id aliquet risus feugiat in ante. Elit duis tristique sollicitudin nibh sit amet. Blandit cursus risus at ultrices mi tempus imperdiet nulla. In eu mi bibendum neque egestas congue. Nibh nisl condimentum id venenatis a condimentum vitae. Id neque aliquam vestibulum morbi. Tincidunt ornare massa eget egestas purus.

                Tempor orci dapibus ultrices in iaculis nunc sed augue lacus. Posuere urna nec tincidunt praesent semper feugiat. Lacinia at quis risus sed vulputate odio. Euismod lacinia at quis risus sed. Et magnis dis parturient montes. Nulla aliquet porttitor lacus luctus accumsan tortor. Pretium lectus quam id leo in vitae. Vitae aliquet nec ullamcorper sit amet. Et tortor at risus viverra adipiscing. Aliquam sem fringilla ut morbi tincidunt. Sed elementum tempus egestas sed sed risus. Odio facilisis mauris sit amet massa vitae tortor. Pellentesque habitant morbi tristique senectus et netus. Cursus mattis molestie a iaculis. Quis risus sed vulputate odio ut enim blandit volutpat. Massa id neque aliquam vestibulum morbi blandit cursus risus. Id porta nibh venenatis cras sed. Ullamcorper eget nulla facilisi etiam dignissim. Faucibus et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Magnis dis parturient montes nascetur.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim blandit volutpat maecenas volutpat. Leo vel fringilla est ullamcorper eget nulla. Venenatis cras sed felis eget velit aliquet sagittis. Lectus arcu bibendum at varius vel pharetra. Tristique nulla aliquet enim tortor at auctor urna nunc. Commodo elit at imperdiet dui accumsan sit amet nulla facilisi. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Et malesuada fames ac turpis egestas sed tempus urna. Elit pellentesque habitant morbi tristique senectus et. Turpis tincidunt id aliquet risus feugiat in ante metus. Erat velit scelerisque in dictum non consectetur a erat nam. Ut eu sem integer vitae justo eget magna fermentum iaculis. A arcu cursus vitae congue mauris rhoncus aenean. Justo nec ultrices dui sapien eget mi proin sed libero. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Facilisis gravida neque convallis a cras semper auctor. In ante metus dictum at tempor commodo ullamcorper.

                Donec ultrices tincidunt arcu non sodales neque. Quis imperdiet massa tincidunt nunc pulvinar. Neque aliquam vestibulum morbi blandit cursus risus. Volutpat odio facilisis mauris sit amet massa vitae tortor. Ornare arcu odio ut sem. Nullam non nisi est sit amet facilisis magna. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Blandit aliquam etiam erat velit scelerisque in dictum non. Facilisi cras fermentum odio eu feugiat pretium. Aliquam id diam maecenas ultricies mi. Ut morbi tincidunt augue interdum velit euismod in pellentesque.

                Nunc aliquet bibendum enim facilisis gravida neque convallis a cras. Auctor augue mauris augue neque gravida in fermentum et. Habitant morbi tristique senectus et netus et malesuada fames ac. Diam vel quam elementum pulvinar etiam non quam. Semper auctor neque vitae tempus quam. Sed enim ut sem viverra aliquet eget sit amet. Sit amet aliquam id diam maecenas. Arcu vitae elementum curabitur vitae nunc. Vitae purus faucibus ornare suspendisse sed nisi lacus. Sed sed risus pretium quam vulputate dignissim suspendisse.

                Pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Tellus orci ac auctor augue mauris augue neque gravida. In hendrerit gravida rutrum quisque non tellus orci ac auctor. Nunc faucibus a pellentesque sit amet porttitor eget. Neque aliquam vestibulum morbi blandit cursus. Diam ut venenatis tellus in metus. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Tempor commodo ullamcorper a lacus vestibulum sed. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget. Maecenas volutpat blandit aliquam etiam. Pretium viverra suspendisse potenti nullam ac tortor vitae purus. Lacus sed turpis tincidunt id aliquet risus feugiat in ante. Elit duis tristique sollicitudin nibh sit amet. Blandit cursus risus at ultrices mi tempus imperdiet nulla. In eu mi bibendum neque egestas congue. Nibh nisl condimentum id venenatis a condimentum vitae. Id neque aliquam vestibulum morbi. Tincidunt ornare massa eget egestas purus.

                Tempor orci dapibus ultrices in iaculis nunc sed augue lacus. Posuere urna nec tincidunt praesent semper feugiat. Lacinia at quis risus sed vulputate odio. Euismod lacinia at quis risus sed. Et magnis dis parturient montes. Nulla aliquet porttitor lacus luctus accumsan tortor. Pretium lectus quam id leo in vitae. Vitae aliquet nec ullamcorper sit amet. Et tortor at risus viverra adipiscing. Aliquam sem fringilla ut morbi tincidunt. Sed elementum tempus egestas sed sed risus. Odio facilisis mauris sit amet massa vitae tortor. Pellentesque habitant morbi tristique senectus et netus. Cursus mattis molestie a iaculis. Quis risus sed vulputate odio ut enim blandit volutpat. Massa id neque aliquam vestibulum morbi blandit cursus risus. Id porta nibh venenatis cras sed. Ullamcorper eget nulla facilisi etiam dignissim. Faucibus et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Magnis dis parturient montes nascetur.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim blandit volutpat maecenas volutpat. Leo vel fringilla est ullamcorper eget nulla. Venenatis cras sed felis eget velit aliquet sagittis. Lectus arcu bibendum at varius vel pharetra. Tristique nulla aliquet enim tortor at auctor urna nunc. Commodo elit at imperdiet dui accumsan sit amet nulla facilisi. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Et malesuada fames ac turpis egestas sed tempus urna. Elit pellentesque habitant morbi tristique senectus et. Turpis tincidunt id aliquet risus feugiat in ante metus. Erat velit scelerisque in dictum non consectetur a erat nam. Ut eu sem integer vitae justo eget magna fermentum iaculis. A arcu cursus vitae congue mauris rhoncus aenean. Justo nec ultrices dui sapien eget mi proin sed libero. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Facilisis gravida neque convallis a cras semper auctor. In ante metus dictum at tempor commodo ullamcorper.

                Donec ultrices tincidunt arcu non sodales neque. Quis imperdiet massa tincidunt nunc pulvinar. Neque aliquam vestibulum morbi blandit cursus risus. Volutpat odio facilisis mauris sit amet massa vitae tortor. Ornare arcu odio ut sem. Nullam non nisi est sit amet facilisis magna. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Blandit aliquam etiam erat velit scelerisque in dictum non. Facilisi cras fermentum odio eu feugiat pretium. Aliquam id diam maecenas ultricies mi. Ut morbi tincidunt augue interdum velit euismod in pellentesque.

                Nunc aliquet bibendum enim facilisis gravida neque convallis a cras. Auctor augue mauris augue neque gravida in fermentum et. Habitant morbi tristique senectus et netus et malesuada fames ac. Diam vel quam elementum pulvinar etiam non quam. Semper auctor neque vitae tempus quam. Sed enim ut sem viverra aliquet eget sit amet. Sit amet aliquam id diam maecenas. Arcu vitae elementum curabitur vitae nunc. Vitae purus faucibus ornare suspendisse sed nisi lacus. Sed sed risus pretium quam vulputate dignissim suspendisse.

                Pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Tellus orci ac auctor augue mauris augue neque gravida. In hendrerit gravida rutrum quisque non tellus orci ac auctor. Nunc faucibus a pellentesque sit amet porttitor eget. Neque aliquam vestibulum morbi blandit cursus. Diam ut venenatis tellus in metus. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Tempor commodo ullamcorper a lacus vestibulum sed. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget. Maecenas volutpat blandit aliquam etiam. Pretium viverra suspendisse potenti nullam ac tortor vitae purus. Lacus sed turpis tincidunt id aliquet risus feugiat in ante. Elit duis tristique sollicitudin nibh sit amet. Blandit cursus risus at ultrices mi tempus imperdiet nulla. In eu mi bibendum neque egestas congue. Nibh nisl condimentum id venenatis a condimentum vitae. Id neque aliquam vestibulum morbi. Tincidunt ornare massa eget egestas purus.

                Tempor orci dapibus ultrices in iaculis nunc sed augue lacus. Posuere urna nec tincidunt praesent semper feugiat. Lacinia at quis risus sed vulputate odio. Euismod lacinia at quis risus sed. Et magnis dis parturient montes. Nulla aliquet porttitor lacus luctus accumsan tortor. Pretium lectus quam id leo in vitae. Vitae aliquet nec ullamcorper sit amet. Et tortor at risus viverra adipiscing. Aliquam sem fringilla ut morbi tincidunt. Sed elementum tempus egestas sed sed risus. Odio facilisis mauris sit amet massa vitae tortor. Pellentesque habitant morbi tristique senectus et netus. Cursus mattis molestie a iaculis. Quis risus sed vulputate odio ut enim blandit volutpat. Massa id neque aliquam vestibulum morbi blandit cursus risus. Id porta nibh venenatis cras sed. Ullamcorper eget nulla facilisi etiam dignissim. Faucibus et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Magnis dis parturient montes nascetur.</div>
        </div>
    )
}
